### ISSUE TITLE
HA MQTT integration unstable?

### ISSUE THREAD

**Issue by darkside90a** [mp-se/kegmon#3]
v0.5.0b7 is installed, and I have tested the Home Assistant MQTT integration.
Does not seem to be very useful at the moment. Just a few telegrams after a reboot. 
I have tested running tcpdump on the HA/Mosquitto Pi. Nothing coming from Kegmon.

Apart from that: Many thanks for yet another useful project you have made!

Cheers
Lars

**Comment by mp-se** [comment]
I've not tested that part that much yet. 

It will only push data when the level or pour has been detected. So I might need to trigger this at more events. 

How would you expect it to work ? What data would you want to see in HA ?

**Comment by darkside90a** [comment]
Ah, I suspected that. I must have wiggled one of the kegs, because I did get name, abv, ibu and ebc from that one time.
It would be nice if a telegram i sent maybe once an hour to confirm the unit is still alive - in addition to when a pour i detected.
For me, name, abv & volume is enough. "Nice to have" are: glasses left and temp

**Comment by mp-se** [comment]
Having data sent on a regular interval is a good idea. Temp should have a more frequent push to track that value, like 5 or 10 min. Glasses left is there as an attribute so you can get that data.

**Comment by mp-se** [comment]
I've done some changes to the HA integration and added so it will push data every 5 minutes when enabled. You can get the 0.5b9 build from the dev branch.

**Comment by mp-se** [comment]
I regard this as closed, please reopen if the issue persists.
