### ISSUE TITLE
Can not get information from BrewSpy

### ISSUE THREAD

**Issue by francoisduprez** [mp-se/kegmon#32]
I don't know if i'm doing something wrong, but i can not get the BrewSpy connection to work.

I made two Taplist entries in BrewSpy and copied the last digits of the webhook into the keg monitor (https://brewspy.app/api/json/taplist/8m2t0qcmdrt9s5dj3r5ncemen4)
But it keeps loading and doesn't fetch any information.

**Comment by mp-se** [comment]
It looks like they have changed the base url so that is why its not working. I will update that in the next release, I'm working on rebuilding the user interface and i have just started the testing part.

**Comment by francoisduprez** [comment]
> It looks like they have changed the base url so that is why its not working. I will update that in the next release, I'm working on rebuilding the user interface and i have just started the testing part.

Ok, thats great. 
I'm glad youre still working on the project, i will wait and see, thanks for the response..

**Comment by mp-se** [comment]
I had a chance to try it out now and it looks it should work. I pasted the last part of the webhook (8m2t0qcmdrt9s5dj3r5ncemen4) in the field and it successfully fetched the data.
