### ISSUE TITLE
Add ability to push data to Barhelper

### ISSUE THREAD

**Issue by wookienow** [mp-se/kegmon#35]
Add the ability to push data to Barhelper for Taplist display
https://barhelper.no/

**Comment by mp-se** [comment]
Do you have any documentation on how there API's looks like ? I could not find anything useful on the URL you shared. 

Normally this should not be a big change to add.

**Comment by mp-se** [comment]
Found the details in the docs.... Will give it a try

**Comment by mp-se** [comment]
There are apparently 2 ways to report data, either the current volume or the detected pour volume... which is to prefer?

**Comment by mp-se** [comment]
You can try this version here; https://github.com/mp-se/kegmon/tree/dev/bin

It updates the volume in Barhelper once there is a stable level. This seamed to be the best option to secure the level is accurate.

**Comment by wookienow** [comment]
Amazing. Will try the binary tonight.

**Comment by wookienow** [comment]
@mp-se I have had a go. I can see in the log when weights change publishing to MQTT and this is working. I  have configured the Barhelper API key but I am not seeing anything in the logs saying it is trying to publish to barhelper. Or anything in barhelper. It looks like it should log in the console in the barhelper.cpp code. 
Any idea what else I could try? Will it work with both configured?

**Comment by mp-se** [comment]
You will get a printout in the serial log when sending data to barhelper, and also the response. Unfortunately the response is not a real json (they have made a misstake) so i cannot parse and check the return. I have reported that problem to the author so we will have to see if they fix that. 

You basically just need to enter the API KEY and have a name for the taps.  The integration will not work without the API KEY.

Data will be posted when there is a stable level and if there is no defined Custom Keg Monitor it will be created. You then need to connect that to a tap/keg.

**Comment by mp-se** [comment]
You can try the new build in the dev branch, it how will show the current status of the transmissions on the main page

**Comment by mp-se** [comment]
The pins are configurable under hardware

**Comment by wookienow** [comment]
I am getting this error. I am able to call the API directly and it works with the same key externally.
Any ideas.

![error](https://github.com/user-attachments/assets/6c678599-c5b0-4027-9df3-44cd01e971e9)
![error](https://github.com/user-attachments/assets/6c678599-c5b0-4027-9df3-44cd01e971e9)

**Comment by mp-se** [comment]
-1 means "connection refused" so do you have a firewall that blocks the request ?

**Comment by wookienow** [comment]
No. Nothing blocking the call. I am calling the API directly from a laptop
on the same network.

**Comment by wookienow** [comment]
Happy to share my API key as well to see if you get the same error as I can always recreate.

**Comment by mp-se** [comment]
Can you see what the output from the serial log is? That should give some more details

**Comment by mp-se** [comment]
Are you using an esp8266 or esp32? Ssl could cause issues on the esp8266 due to lack of memory

**Comment by wookienow** [comment]
Logs appear to be getting cut off but this is what is shown (2 examples below)

` 953097 I: HA  : Sending POUR information to HA, pour 0.52l [0].
    953101 I: TPL : Buffer needed 390.
    953217 I: LVL : Logging level change    953245 I: TPL : Buffer needed 507.
    953339 I: PUSH: MQTT publish success    953397 I: HA  : Sending TAP informat    953442 I: PUSH: Sending values to mq    953521 I: BARH: Sending TAP informat    953663 I: PUSH: Adding header 'Content-Type': 'application/json'
    953664 I: PUSH: Adding header 'Autho    953694 E: PUSH: HTTP post failed, re    955078 I: LOOP: Reading data raw1=0.47,raw2=0.00,stable1=0.46, stable2=0.00,pour1=0.52,pour2=nan
    `
```

`53097 I: HA  : Sending POUR information to HA, pour 0.52l [0].
    953101 I: TPL : Buffer needed 390.
    953217 I: LVL : Logging level change    953245 I: TPL : Buffer needed 507.
    953339 I: PUSH: MQTT publish success    953397 I: HA  : Sending TAP informat    953442 I: PUSH: Sending values to mq    953521 I: BARH: Sending TAP informat    953663 I: PUSH: Adding header 'Content-Type': 'application/json'
    953664 I: PUSH: Adding header 'Autho    953694 E: PUSH: HTTP post failed, re    955078 I: LOOP: Reading data raw1=0.47,raw2=0.00,stable1=0.46, stable2=0.00,pour1=0.52,pour2=nan
```

**Comment by wookienow** [comment]
Wemos D1 Mini 8266

**Comment by mp-se** [comment]
Can you check how much free memory you have on the dashboard ?

**Comment by mp-se** [comment]
Then its a memory problem. SSL requires 22kb free memory to work. You need an esp32s3 or esp32s2 mini for that to work

**Comment by wookienow** [comment]
Thanks, I have 1 floating around will change it over and check but will be
tomorrow. Do you think there would be anything I could remove from the
codebase to free up memory so I don't have to replace it in all my scales?

**Comment by mp-se** [comment]
You can try to run it without having any interaction with the UI that would help. The webserver and the api communication will consume quite a lot of memory. You can check the memory usage by accessing the http://deviceid/api/status that will give the raw json data. If that has more than 22kb memory free than it should work to update via ssl.

**Comment by mp-se** [comment]
On my other projects only allow for SSL when the webserver is not used so that there is enough memory to run.... but remove the webserver would make it difficult to manage the configuration....

**Comment by mp-se** [comment]
I just tested to call the API without SSL and that worked. I could change the code so on esp8266 it does not use SSL when calling barhelper, that could fix the problem. Not sure how long they will allow that....

**Comment by wookienow** [comment]
I am willing to give it a go. Not using the web access didn't free up any memory. Not sure if it loads even if it isn't being accessed.

**Comment by mp-se** [comment]
I will do the change after work and let you know when there is a new build to test

**Comment by wookienow** [comment]
Tested this morning before work and seems to work now. Looks like you
nailed the reason why. Will do some more testing tonight but that is for
all the effort and the quick response.

**Comment by wookienow** [comment]
This works really well and data now flowing through.
Would be great if in the future it supported SSL as well but understand the mem requirements.
I found one other minor issue when configuring and have another enhancement request I will log these seprately.
